# This file was generated by GoReleaser. DO NOT EDIT.
cask "avro-gen-go-mcp" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0555016cd5eef34ba6b744519566177c661dcaffe693c33b9a8eb0900d83d213"
      url "https://github.com/dipjyotimetia/kafka-avro-mcp/releases/download/v#{version}/kafka-avro-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "56f1415a19fbeb71e7a5cccadfbda84047617795b146d60fbe4d33fc6462f8d8"
      url "https://github.com/dipjyotimetia/kafka-avro-mcp/releases/download/v#{version}/kafka-avro-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3effafe84f5569d9e362c1176cad9a826d12d26afa831d07df1332093320f3e2"
      url "https://github.com/dipjyotimetia/kafka-avro-mcp/releases/download/v#{version}/kafka-avro-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0c135301ae5adee032649623e14d7996e7d74ba54f224a21ec448f506997c17"
      url "https://github.com/dipjyotimetia/kafka-avro-mcp/releases/download/v#{version}/kafka-avro-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "avro-gen-go-mcp"
  desc "Avro event contract → static Go MCP Kafka publish tools generator"
  homepage "https://github.com/dipjyotimetia/kafka-avro-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "avro-gen-go-mcp"

  # No zap stanza required
end
