# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-go-mcp" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "5450e730abc7f5e8cf6b30c255124a8769e42b68222c1c9b4dd365b2d344d929"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7b05feda6486dc60164624e5d9f840c66313363bdaee9ee90426867a562210a"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7a0f665d799657f21defee2c72b7c14b6782056fb36b87e111901df430f41ca"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4197d0d4cc904affc8a88c68d667e78308006017b4a683c5aa930b795780ca07"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openapi-go-mcp"
  desc "OpenAPI 3.x / Swagger 2.0 → Go MCP code generator"
  homepage "https://github.com/dipjyotimetia/openapi-go-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-go-mcp"

  # No zap stanza required

end
