# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-go-mcp" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "0e1f80d1a3085db0eb306498bc9f406d375c27f1b4b3ccb7cedeff24f7a428f8"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "01eed54e8990a27630fc04ea4b4be9e2b7e4c8b39028c257333f3203e2cf43ab"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6d9c54729bf85cb3b5f11db7a1b06e96a912c254d8627b18ad2ff301d503f92c"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31ae6d22de82e96ba467aa01dd3c9d30d05c7dacaf4b2890db73d418b8188221"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "openapi-go-mcp"
  desc "OpenAPI 3.x / Swagger 2.0 → Go MCP code generator"
  homepage "https://github.com/dipjyotimetia/openapi-go-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-go-mcp"

  # No zap stanza required
end
