# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-go-mcp" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "2cb1e39856585ae3d80f28d468b5d4d022395e30a004846b781ad21fe7b89083"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f21104994f1bb8e31d73d5d4eae784f74891371b511357e6f16fbf8bbfa2c68a"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe8297b29c5bda3c65bd7f6a1a43941edc4bdb5a228902ae7130e438c8e2e0d3"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd473ae80fde7748669a590fa61cada84723805213d42cedb5e19492ccef9668"
      url "https://github.com/dipjyotimetia/openapi-go-mcp/releases/download/v#{version}/openapi-go-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openapi-go-mcp"
  desc "OpenAPI 3.x / Swagger 2.0 → Go MCP code generator"
  homepage "https://github.com/dipjyotimetia/openapi-go-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-go-mcp"

  # No zap stanza required

end
