# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-gen-go-mcp" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a0e5f7b8cfa93eb75c1bcc4d1fa0eb94bbae5d97aabd82b7f473ddc1d32db89c"
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v#{version}/openapi-gen-go-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "50869ece97e0c9922653abddf50b15e17d19813605e7caf4a1637b681d9f9078"
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v#{version}/openapi-gen-go-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69bce4cfe915bc1e86ae82dbc42f7023b0e4f9c330ce2bd928d3b09c2d817d7b"
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v#{version}/openapi-gen-go-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "49937b286e1e537a29f88fa2ea3d9c73dfdc85bed2dd465c5c7311030ddbff0b"
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v#{version}/openapi-gen-go-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openapi-gen-go-mcp"
  desc "OpenAPI 3.x / Swagger 2.0 → Go MCP code generator"
  homepage "https://github.com/dipjyotimetia/openapi-gen-go-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-gen-go-mcp"

  # No zap stanza required

end
