# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenapiGenGoMcp < Formula
  desc "OpenAPI 3.x / Swagger 2.0 → Go MCP code generator"
  homepage "https://github.com/dipjyotimetia/openapi-gen-go-mcp"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v0.1.0/openapi-gen-go-mcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "3e68eda1fa6f312a4eb4e20d02b3799c0b6413958fdb72d4e419ac662735e6c4"

      define_method(:install) do
        bin.install "openapi-gen-go-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v0.1.0/openapi-gen-go-mcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "37bdd1ff89fe2499c7baa2f749e1404d11ba6561a8ec23cdad3c89a77b7213a6"

      define_method(:install) do
        bin.install "openapi-gen-go-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v0.1.0/openapi-gen-go-mcp_0.1.0_linux_amd64.tar.gz"
      sha256 "607383433afdc3b0457423efa006b0b3a9983bb7cd80bc3d2a471cb951a8cf87"
      define_method(:install) do
        bin.install "openapi-gen-go-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dipjyotimetia/openapi-gen-go-mcp/releases/download/v0.1.0/openapi-gen-go-mcp_0.1.0_linux_arm64.tar.gz"
      sha256 "199227bb3a3e5351dba6e2e2d1a4ec81d14faa796ce5d66121e04d62ac52ed6d"
      define_method(:install) do
        bin.install "openapi-gen-go-mcp"
      end
    end
  end

  test do
    system "#{bin}/openapi-gen-go-mcp", "-h"
  end
end
